using System.ComponentModel;

namespace ICStars2_0.Model.Enum
{
    public enum StateType
    {
        [Description("Alabama")] Alabama,
        [Description("Alaska")] Alaska,
        [Description("Arizona")] Arizona,
        [Description("Arkansas")] Arkansas,
        [Description("California")] California,
        [Description("Colorado")] Colorado,
        [Description("Connecticut")] Connecticut,
        [Description("Delaware")] Delaware,
        [Description("Florida")] Florida,
        [Description("Georgia")] Georgia,
        [Description("Hawaii")] Hawaii,
        [Description("Idaho")] Idaho,
        [Description("Illinois")] Illinois,
        [Description("Indiana")] Indiana,
        [Description("Iowa")] Iowa,
        [Description("Kansas")] Kansas,
        [Description("Kentucky")] Kentucky,
        [Description("Louisiana")] Louisiana,
        [Description("Maine")] Maine,
        [Description("Maryland")] Maryland,
        [Description("Massachusetts")] Massachusetts,
        [Description("Michigan")] Michigan,
        [Description("Minnesota")] Minnesota,
        [Description("Mississippi")] Mississippi,
        [Description("Missouri")] Missouri,
        [Description("Montana")] Montana,
        [Description("Nebraska")] Nebraska,
        [Description("Nevada")] Nevada,
        [Description("New Hampshire")] New_Hampshire,
        [Description("New Jersey")] New_Jersey,
        [Description("New Mexico")] New_Mexico,
        [Description("New York")] New_York,
        [Description("North Carolina")] North_Carolina,
        [Description("North Dakota")] North_Dakota,
        [Description("Ohio")] Ohio,
        [Description("Oklahoma")] Oklahoma,
        [Description("Oregon")] Oregon,
        [Description("Pennsylvania")] Pennsylvania,
        [Description("Rhode Island")] Rhode_Island,
        [Description("South Carolina")] South_Carolina,
        [Description("South Dakota")] South_Dakota,
        [Description("Tennessee")] Tennessee,
        [Description("Texas")] Texas,
        [Description("Utah")] Utah,
        [Description("Vermont")] Vermont,
        [Description("Virginia")] Virginia,
        [Description("Washington")] Washington,
        [Description("West Virginia")] West_Virginia,
        [Description("Wisconsin")] Wisconsin,
        [Description("Wyoming")] Wyoming

    }
}
