
Create table CommunityInternship
(
	ID int identity(1,1) primary key,
	Name VARCHAR(50) not null,
	[Address] varchar(200) not null,
	Depaul_ID_Number varchar(20) not null,
	Birth_Date Datetime not null,
	Gender varchar(10) not null,
	Home_Phone_Number varchar(20) not null,
	Cell_Phone_Number varchar(20) not null,
	Email varchar(200) not null,
	Racial_Background varchar(100) not null,
	DePaul_Expected_Graduation_Date datetime not null,
	College varchar(500) not null,
	Major_Area_Of_Academic_Focus varchar(200) not null,
	Minor_Area_Of_Academic_Focus varchar(200) not null,
	Community_Based_Service_Learning_Courses_Previously_Taken_At_DePaul varchar(1000) not null,
	Service_Community_Work_Involved_Since_Enrollment_At_DePaul varchar(1000) not null,
	How_Internship_Relates_To_A_Course_Research_Project_Academic_Pursuit varchar(1000) not null,
	How_will_this_experience_relate_to_your_personal_academic_career_goals varchar(1000) not null,
	Specific_learning_goals1 varchar(1000) not null,
	Specific_learning_goals2 varchar(1000) not null,
	Specific_learning_goals3 varchar(1000) not null,
	References_Academic varchar(1000) not null,
	References_Other varchar(1000) not null,
	Preferred_Site1 varchar(1000),
	Preferred_Site2 varchar(1000),
	Intern_Sign varchar(50) not null,
	Intern_Sign_Date datetime not null,
	Site_Supervisor varchar(50) not null,
	Site_Supervisor_Date datetime not null,
	Instructor varchar(50) not null,
	Instructor_Date datetime not null,
	QuarterYear varchar(50),
	QuarterYearOrder int
)