
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Better Boys Foundation','KidLab','1512 S Pulaski Rd, Chicago, IL 60623',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Better Boys Foundation','YouthLAB','1512 S. Pulaski Road Chicago, IL 60623',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Better Boys Foundation','Referral Development','1512 S. Pulaski Road Chicago, IL 60623',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Calor','Communtiy Health Education','5038 W. Armitage, Chicago, IL ',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Christ the King','Health Education','5088 W. Jackson, Chicago, IL 60653',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Community Partnerships of Illinois (CPOFIL)','Clinical Data Review','205 West Randolph, Suite 2222, Chicago, IL 60606 ',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'CommunityHealth','Health Education','2611 W Chicago Ave. Chicago, IL  60622',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'CommunityHealth','Health Education','2611 W Chicago Ave. Chicago, IL  60622',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'CommunityHealth','STDs/Vaccines','2611 W Chicago Ave. Chicago, IL  60622',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'CommunityHealth','Interpreting','2611 W Chicago Ave. Chicago, IL  60622',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'El Valor ','Residential Services','1924 W. 19st Street Chicago, IL 60608',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'El Valor ','Brain Injury','1924 W. 21st. Street Chicago, IL 60608',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'El Valor ','Developmental Training','1924 W. 21st. Street Chicago, IL 60608',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'El Valor ','Guadalupe Reyes','1951 W. 19th Street, Chicago, IL 60608',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'El Valor ','Rey B. Gonzalez','3050 E. 92nd Street, Chicago, IL 60617',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'El Valor ','Carlos H. Cantu ','2434 S. Kildare Avenue, Chicago, IL 60623',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Harbour ','Successful Teens/Effective Parents','1440 Renaissance Drive, Set 240, Park Ridge, IL 60068',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Healthcare Alternative Systems (HAS)','Armitage Avenue (IOP/OP/Women’s)','2755 W. Armitage, Chicago, IL 60647',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Hephzibah Children’s Association','Youth Group Home Support','946 North Boulevard, Oak Park, IL',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Jewish Child & Family Services (JCFS)','Recreation','West Rogers Park',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Life Directions ','Peer Mentor Program ','404 S. Homan St. – 2nd Floor Chicago, Il 60624 ',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Marillac Social Center','Outreach','212 S Francisco Ave, Chicago, IL 60612',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Near West Side Community Development Corporation','Family Engagement and Community Mapping','216 S. Hoyne Chicago, IL 60612',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Near West Side Community Development Corporation','Family Works','125 N. Hoyne, Chicago, Il, 60612',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Northwest Side Housing Center ','Outreach','5007 W Addison St, Chicago, IL 60641',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Old Irving Park ','Clinic Support','5425 W Addison St, Chicago, IL 60641',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Scleroderma Foundation','Fundraising','134 N. LaSalle St. Suite 1360 Chicago, IL 60602',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Scleroderma Foundation','Patient Education','134 N. LaSalle St. Suite 1360 Chicago, IL 60602',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'Scleroderma Foundation','Marketing','134 N. LaSalle St. Suite 1360 Chicago, IL 60602',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'St. Vincent de Paul Center','Health Trainings','2145 N Halsted, Chicago, IL 60614',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','215 W. Miner Street Arlington Heights, IL 60005',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','1314 Wentworth Avenue Chicago Heights, IL  60411',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','1704 E. End Avenue Chicago Heights, IL 60411',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','1704 E. End Avenue Chicago Heights, IL 60411',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','1314 Wentworth Avenue Chicago Heights, IL 60411',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','1314 Wentworth Avenue Chicago Heights, IL 60411',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','1301 Ashland Avenue Des Plaines, IL 60016',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','1900 Sherman Avenue Evanston, IL 60201',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','2300 Noyes Court Evanston, IL 60201',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','1055 Berkeley Ford Heights, IL 60411',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','9535 W. Franklin Avenue Franklin Park, IL 60131',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','15306 S. Robey Harvey, IL 60426',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','9201 Maryland Avenue Niles, IL 60714',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','350 Juniper Street Park Forest, IL 60466',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','3210 W. 139th Street Robbins, IL  60472',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','13900 Grace Street Robbins, IL  60472',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','9238 Gross Point Road Skokie, IL 60077',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','7455 W. 63rd Place Summit, IL 60501',0;
insert into son_cboprogram(cboname,ProgramName,location,Slots) select 'The Housing Authority of Cook County ','Education Workshops','200 N. Milwaukee Avenue Wheeling, IL 60090',0;
