insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program #1: Family Services',2,'Not Required','1448 Wesley Ave Berwyn, IL 60402';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 2: Head Start – Health and Disability',1,'Not Required','651 W Lake St Chicago, IL 60661';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 2: Head Start – Health and Disability',1,'Not Required','4800 S Paulina StChicago, IL 60609';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 2: Head Start – Health and Disability',1,'Not Required','5332 S Western Blvd Chicago, IL 60609';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 2: Head Start – Health and Disability',1,'Not Required','2414 S Albany AveChicago, IL 60623';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 2: Head Start – Health and Disability',1,'Not Required','1449 S Keeler AveChicago, IL 60623';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 2: Head Start – Health and Disability',1,'Not Required','3001 W 59th St Chicago, IL 60629';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 3: Head Start – Site Specific Assignment',2,'Not Required','4800 S Paulina StChicago, IL 60609';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 3: Head Start – Site Specific Assignment',2,'Not Required','5332 S Western Blvd Chicago, IL 60609';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 3: Head Start – Site Specific Assignment',2,'Not Required','2414 S Albany Ave Chicago, IL 60623';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 3: Head Start – Site Specific Assignment',2,'Not Required','1449 S Keeler Ave Chicago, IL 60623';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 3: Head Start – Site Specific Assignment',2,'Not Required','3001 W 59th St Chicago, IL 60629';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 4: Child Care (not Head Start)',1,'Not Required','1448 Wesley Ave Berwyn, IL 60402';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 4: Child Care (not Head Start)',1,'Not Required','7438 W. 61st, Summit, IL 60501';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program # 4: Child Care (not Head Start)',1,'Not Required','1100 S May StChicago, IL 60607';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Casa Catalina Basic Human Needs Center',2,'Not Required','4537 S Ashland AveChicago, IL 60636';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' WIC Food and Nutrition Programs',2,'Not Required','5332 S Western AveChicago, IL 60609';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' WIC Food and Nutrition Programs',2,'Not Required','2400 S Kedzie Ave Chicago, IL 60623';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' WIC Food and Nutrition Programs',2,'Not Required','4622 W Diversey AveChicago, IL 60639';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' WIC Food and Nutrition Programs',2,'Not Required','3110 W Armitage AveChicago, IL 60647';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Maternity/Adoption',2,'Not Required','651 W Lake StChicago, IL 60661';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program #1: Catholic Home Care',4,'Not Required','721 N LaSalle StChicago, IL 60654';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program #2: Adult Day Services',2,'Not Required','6717 S Elizabeth StChicago, IL 60636';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program #2: Adult Day Services',2,'Not Required','9249 S Avalon AveChicago, IL 60619';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program #2: Adult Day Services',2,'Not Required','112 N Humphrey AveOak Park, IL 60302';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program #3: Senior Centers',1,'Not Required','653-657 W. 63rd, Chicago, IL 60621';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program #3: Senior Centers',1,'Not Required','1700 Memorial Dr Calumet City, IL 60409';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CC',' Program #3: Senior Centers',1,'Not Required','4040 N Oakley AveChicago, IL 60618';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'HAS',' Program #1: Medication Assisted Program',3,'Yes, Spanish Preferred','210 N Ashland Ave Chicago, IL 60612';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'HAS',' Program  #2: Western Avenue (IOP/OP/PPD/Youth',3,'Yes, Spanish Preferred','4534 S Western AveChicago, IL 60609';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'HAS',' Program  #3: Armitage Avenue (IOP/OP/Women’s)',3,'Yes, Spanish Preferred',' 2755 W Armitage AveChicago, IL 60647';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'HAS',' Program #4: Residence and Transitional Housing',3,'Yes, Spanish Preferred','1949 N Humboldt BlvdChicago, IL 60647';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'AHA',' Program #1: Community Health',1,'Not Required','208 s LaSalle, Suite 1500, Chicago, IL 60604';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'AHA','Program  #2: Heart 360 ',1,'Not Required','208 s LaSalle, Suite 1500, Chicago, IL 60604';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'AHA','Program #3: Go Red Por Tu Corazon',1,'Spanish Required','208 s LaSalle, Suite 1500, Chicago, IL 60604';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'AC','Program  #1: Stuart G. Ferst School',1,'Not Required','6050 N California Ave Chicago, IL 60659';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'RCS','Program  #1: SMILE Dental Education and Oral Hygiene',1,'Not Required','550 N Hermitage Ave Chicago, IL 60640';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'RCS','Program #2: Meal and Pantry Program/Health Outreach Clinic',2,'Not Required','550 N Hermitage Ave Chicago, IL 60640';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'LPCS','Program #1: Interim Housing Community',10,'Not Required','600 W Fullerton Parkway, Chicago IL 60614';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'ICAH','Program #1: Adult & Professional Development Education',4,'Not Required','226 S. Wabash Ave. Suite 900, Chicago, IL 60604';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CH','Program #1: Women’s Health',1,'Yes, Spanish Preferred','2611 W Chicago Ave Chicago, IL 60622';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CH','Program #2: Men’s Health and Colorectal Health',1,'Not Required','2611 W Chicago Ave Chicago, IL 60622';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CH','Program #3:  Englewood Preventative Screenings & Vaccines',1,'Not Required','641 W 63rd St Chicago, IL 60621';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CH','Program #4: Quality Management Data Collection',1,'Not Required','2611 W Chicago Ave Chicago, IL 60622';
insert into son_cboprogram(CBOName,ProgramName,Slots,Bilingual,Location) select 'CH','Program #5: Health Education',2,'Yes, Spanish & Polish Required','2611 W Chicago Ave Chicago, IL 60622';

