create table HistoricalFaculty
(
		ID int identity(1,1),
		EmpId varchar(20),
		FirstName varchar(50) not null,
		LastName varchar(50) not null,
		Email varchar(250),
		constraint HistoricalFaculty_ID PRIMARY KEY(
		ID
		)
)
select * from HistoricalFaculty
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Alter','Gloria',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1399106','Amer','Kim','kamer@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '672993','Andolina','Molly','mandolin@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1341288','Arents','Jerica','jerica.arents@gmail.com'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1341288','Arents','Jerica','jerica.arents@gmail.com'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '406937','Barker','Noel','nbarker@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '852296','Bartling','Hugh','hbartlin@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1063775','Black','Monika','mblack7@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Bothne','Nancy',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '408572','Bowden','Darsie','dbowden@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Brooks','John',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1177521','Burgo','Clara','CBURGO@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '859123','Butigan','Kenneth','kenbutigan@gmail.com'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '616875','Carter','Jeff','jcarter@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '618473','Catlett','Beth','bcatlett@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1085962','Ceraso','Antonio','ACERASO@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Cohen','Adar',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Cohen','Jennifer',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1287386','DeBerry','Misty','mdeberry@colum.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Demeter','Dana','dana_demeter@yahoo.com'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','DiPierro','Massimo',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '701946','Dolan','Maureen','mdolan1@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '617657','Doody','Colleen','cdoody@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '699042','Edwards','Michael','medward4@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Elber','Josie',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Elder','Mark',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1377748','Engbers','Trent','tengbers@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '407208','Farah','Laila','lfarah@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '616569','Ferreira','Rocio','rferreir@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1192378','Ferrera','Maria','mferrera@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Gardner','Joseph',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1194787','Garneau','Nicole','nicolegarneau13@sbcglobal.net'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '703217','Giles','Susan','sgiles@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '710395','Glantsman','Olya','oglantsm@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '408863','Goergen','Juana','jgoergen@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Gonsalez','Teresea',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Graupmann','Verena',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '106906','Grossman','Nancy','ngrossma@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '612720','Gulasingam','Nandhini','MGULASIN@DEPAUL.EDU'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Gutierrez','Robert',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '784664','Hague','Euan','ehague@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1003538','Harris','Barbara','bharri14@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1396740','Hinojosa','Maria','MHINOJO2@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1220703','Howard','Jeffrey','jhowar15@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1029561','Hwang','Sungsoon','shwang9@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1307452','Johnsen','Krista','coachkrista@gmail.com'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '877151','Johnson','Valerie','vjohnso5@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '673897','Kachiroubas','Nicholas','pres_48@hotmail.com'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '148283','Kagan','Paula','pkagan@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Kowalkowski','Jeff',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '208763','Kowalkowski','Jeffrey','jkowalko@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1286434','Kumar','Sujith','skumar20@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '192382','Lanterman','Margaret','mlanterm@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '402171','LaVan','Helen','hlavan@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '401234','Layton','Azza','alayton@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '701846','Lazu','Jacqueline','jlazu@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1225462','Leavy','Elizabeth','eleavy@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Legato','Lauren',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1341689','Light','Mark','mark@marklight.com'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '163135','Lindsay-Ryan','Elisabeth','elindsay@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '407429','Lindsey','Howard','hlindsey@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '240866','LoSardo','Betta','blosardo@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '131915','Luhrs','Theresa','tluhrs@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1194380','Markley','Melissa','mmarkley@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '741284','Martin','William','martym@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '401405','Masud-Piloto','Felix','fmasud@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '197608','Moe','Dominica','dmoe@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '156098','Morales','Marisol','mmorale1@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '849511','Morano','Michele','mmorano@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '784686','Mora-Torres','Juan','jmorator@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '408457','Murphy','Alexandra','amurphy1@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '817373','Murphy','James',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '616581','Nass','Karl','knass@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1398972','Ng','Jerome','jng14@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '616606','Niro','Brian','bniro@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '675622','Olison','Willona','wolison@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '817373','Rakes','Heather','HRAKES@DEPAUL.EDU'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1327906','Read','Sarah','sread@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Reed','Monique',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '401979','Reed','Susan','sreed@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Rieckhoff','Barbara',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '400169','Rinehart','Lucy','lrinehar@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '702083','Rosing','Howard','hrosing@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '795246','Rubin','Robert','rrubin@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1420005','Rylance','Kathleen','kbrylance@gmail.com'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1383747','Schlichtman','John','jschlich@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1336877','Shattell','Mona','mona.shattell@gmail.com'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '982738','Sillas','Melanie','msillas@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Sisul','Paul',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '945501','Smith','Heather','heathersmithchicago@gmail.com'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Steinbach','Terry',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '402185','Steinberg','Naomi','nsteinbe@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1042854','Stout','Marcia','mstout1@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '401012','Strain','Charles','cstrain@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '769790','Tavanti','Marco','mtavanti@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '1341373','Thomas','Lisa','lthoma41@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '919667','Triller','Steffanie','striller@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '923751','Tzoumis','Kelly','kellytzoumis@gmail.com'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '','Weiner','Deborah',''
insert into HistoricalFaculty (empid,firstname,lastname,email) select '105913','Wills','Shana','swills@depaul.edu'
insert into HistoricalFaculty (empid,firstname,lastname,email) select '151103','Wright','Melinda','mwright3@depaul.edu'
