create table ServiceLearnersApplication
(
	ID int identity(1,1) primary key,
	QuarterYear varchar(50),
	Region varchar(100),
	OrganizationName varchar(200) not null,
	[Address] varchar(200) not null,
	ServeCommunities varchar(500),
	ServiceAddress varchar(200),
	Directions_PublicTransportation varchar(500),
	Directions_Car varchar(500),
	Directions_Street_or_Lot_Parking varchar(500),
	Phone varchar(100),
	Fax varchar(100),
	Website varchar(300),
	Leadership_ExecutiveDirectorName varchar(100),
	Leadership_WorkPhone varchar(100),
	Leadership_CellPhone varchar(100),
	Leadership_Email varchar(200),
	Leadership_How_long_served varchar(200),
	Representative_Name varchar(100) not null,
	Representative_Title varchar(200) not null,
	Representative_Department_Program varchar(200) not null,
	Representative_NameofDirectSupervisor varchar(100) not null,
	Representative_Address varchar(200) not null,
	Representative_workPhone varchar(100) not null,
	Representative_CellPhone varchar(100) not null,
	Representative_Email varchar(200) not null,
	Representative_ContactMode varchar(100) not null,
	OrganizationalMission varchar(1000),
	PrimaryPopulationServed varchar(1000),
	PrimaryPopulationServed_EthnicCommunitySpecific varchar(200),
	PrimaryPopulationServed_Other varchar(200),
	MajorProgramsServicesProvided varchar(1000),
	MajorProgramsServicesProvided_Other varchar(200),
	ServiceInterestOpportunities_ServiceMode varchar(100),
	ServiceInterestOpportunities_InterestedInCommunitybasedResearchProjects varchar(100),
	ServiceInterestOpportunities_Task1 varchar(200),
	ServiceInterestOpportunities_Task1_Description varchar(1000),
	ServiceInterestOpportunities_Task1_NumberofStudents varchar(100),
	ServiceInterestOpportunities_Task1_AvailabilityNeeded varchar(200),
	ServiceInterestOpportunities_Task2 varchar(200),
	ServiceInterestOpportunities_Task2_Description varchar(1000),
	ServiceInterestOpportunities_Task2_NumberofStudents varchar(100),
	ServiceInterestOpportunities_Task2_AvailabilityNeeded varchar(200),
	ServiceInterestOpportunities_Task3 varchar(200),
	ServiceInterestOpportunities_Task3_Description varchar(1000),
	ServiceInterestOpportunities_Task3_NumberofStudents varchar(100),
	ServiceInterestOpportunities_Task3_AvailabilityNeeded varchar(200),
	ServiceInterestOpportunities_Task4 varchar(200),
	ServiceInterestOpportunities_Task4_Description varchar(1000),
	ServiceInterestOpportunities_Task4_NumberofStudents varchar(100),
	ServiceInterestOpportunities_Task4_AvailabilityNeeded varchar(200),
	ServiceInterestOpportunities_BackgroundChecks_RequireVolunteers varchar(100),
	ServiceInterestOpportunities_BackgroundChecks_BackgroundCheck bit,
	ServiceInterestOpportunities_BackgroundChecks_BackgroundCheckApprovalTime datetime,
	ServiceInterestOpportunities_BackgroundChecks_TBTesting bit,
	ServiceInterestOpportunities_BackgroundChecks_TBTestingApprovalTime datetime,
	ServiceInterestOpportunities_BackgroundChecks_Fingerprinting bit,
	ServiceInterestOpportunities_BackgroundChecks_FingerprintingApprovalTime datetime,
	SiteRepresentativeCommitment_PresentationQuarter varchar(100),
	SiteRepresentativeCommitment_ScheduleOrientation varchar(100),
	SiteRepresentativeCommitment_TimeCommitment varchar(100),
	SiteRepresentativeCommitment_Feedback varchar(100),
	SiteRepresentativeCommitment_DePaulPartnersListserv varchar(100),
	Name varchar(100),
	Title varchar(100),
	[Date] datetime,
	CurrentSteansCenterContact varchar(100)
	
	
)