insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'LL','302-907','EXTERNSHIP','Lindsay-Ryan, Elisabeth',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'CSS','201-301','PERSPECTIVES/COMMUNITY SERVICE','Lazu, Jacqueline',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'CSS','300-301','INTRODUCTION TO NON PROFIT MANAGEMENT','',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'PSY','354-301','COMMUNITY PSYCHOLOGY','',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'SOC','212-301','COMMUNITY AND SOCIETY','',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'PSY','356-301','PRINCIPLES OF FIELD RESEARCH AND ACTION','',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'PSY','306-301','SERVICE LEARNING: MENTAL HEALTH PROBLEMS IN CONTEMPORARY SOCIETY','',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'CSS','201-302','PERSPECTIVES/COMMUNITY SERVICE','Murphy, Alexandra',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'MUS','107-301','GUIDE TO MUSIC THEORY','Kowalkowski, Jeffrey',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'MUS','203-301','CONTEMPORARY IMPROVISATION','Kowalkowski, Jeffrey',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'ART','215-301','INTERMEDIATE SCULPTURE','Carter, Jeff',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'ART','315-301','ADVANCED SCULPTURE','Carter, Jeff',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'SPN','116-301','Intermediate Spanish for Heritage Speakers III','Ferreira, Rocio',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'LSP','121-315','Quantitative Reasoning and Technogy Literacy II','Sisul, Paul',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'CSS','101-301','Catholic Social Teaching','Nass, Karl',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'PAX','220-901','Activism','Arents, Jerica',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'CSS','395-901','Community Internship','Sillas, Melanie',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'PAX','200-301','Perspectives on Peace/Justice/Conflict Resolution','Butigan, Ken',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'PAX','200-901','Perspectives on Peace/Justice/Conflict Resolution','Dolan, Maureen',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'GEO','133-601','Urban Geo-experiential Learning','Hague, Euan',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'PAX','212-301','Social Justice/Social Change','Goergen, Juana',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'LST','303-301','Border Matters','Goergen, Juana',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'WRD','542-301','Urban Literacies','Bowden, Darcie',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'PRAD','337-901','Public Relations Campaigns','Brooks, John',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'ART','291-901','Mural Painting','Elder, Mark',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'ART','383-901','Service Learning in the Arts Internship','Elder, Mark',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'ART','283-301','Integrating Arts and Community','Lanterman, Margaret',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'REL','259-301','Religion and Social Engagement','Steinberg, Naomi',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'MGT','523-301','Recruitment and Selection','Rubin, Robert',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'CSC','378-801','Software Projects for Community Partners','Steinbach, Theresa',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'CMNS','527-301/HTHC-519-301','Assessment and Intervention in Organizations','Olison, Willona',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'SEC','328-901/T&L-428-901','Teaching Literature','Weiner, Deborah',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'MLS','490-303','SPECIAL TOPICS AND CONTROVERSIES- GEOGRAPHY, FOOD & JUSTICE','',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'ASL','203-301','Advanced Communication III','Demeter, Dana',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'SPN','126-301','Intermediate Spanish','Burgo, Clara',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'WGS','480-301','Selected Topics: Women, Self, and Society - Performance/Practice/Resistance','DeBerry, Misty',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'PHL','250-101','Philosophy & Social Change: The Prison System','Rakes, Heather',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'CSS','310-301','Restorative Justice: Engagement with the Prison','Moe, Dominica',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'PSY','305-301','Psychology & Social Justice','Bothne, Nancy',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'SOC','394-301','Community-based Sociology: Paths To And Away From Prison','Barker, Noel',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'GEO','242-901','Geographic Information Systems II: Community GIS','Gulasingam, Nandhini',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'ART','115-301','BEGINNING SCULPTURE','Giles, Susan',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'NSG','400-301','THEORETICAL COMPONENTS OF NURSING','Shatell, Mona',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'NSG','400-302','THEORETICAL COMPONENTS OF NURSING','Kagan, Paula',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'NSG','400-303','THEORETICAL COMPONENTS OF NURSING','Harris, Barbara',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'NSG','431-301','HEALTH PROMOTION FOR FAMILIES AND COMMUNITIES','Stout, Marcia',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'NSG','431-302','HEALTH PROMOTION FOR FAMILIES AND COMMUNITIES','Rylance, Kathleen',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'A&S','493-301','Data Driven Decision Making','Rieckhoff, Barbara',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'LL','302-901','EXTERNSHIP (32888)','Howard, Jeffrey',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'LST','310-301','SPEC/TOPICS: LATINOS IN U.S. (34118)','Hinojosa, Maria',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'IN','345-901','EXTERNSHIP:ANIMALS/CONTMP LIFE (32749)','LoSardo, Betta',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'MPS','614-301','GLOBAL/CIVIL SOCIETY ORGANIZ (34330)','Tavanti, Marco',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'TCH','320-302','EXPLORING TEACHING IN URBAN HS (31178)','Cohen, Jennifer',0,'selahi1','Spring 2013';
insert into course ([Subject],CatalogNumber,Title,InstructorName,[Type],Staff,TermDescription) select 'SPN','393-301','LATINO MEDIA AND DIGITAL CULTURE LITERACY','Jacqueline Lazu',0,'selahi1','Spring 2013';

